apiVersion: v1
kind: Service
metadata:
  name: echo-api
  namespace: echo
  labels:
    app.kubernetes.io/name: echo-api
    app.kubernetes.io/part-of: echo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: echo-api
  ports:
    - name: http
      port: 80
      targetPort: http
